### ISSUE TITLE
Caster error: "Can't assign requested address"

### ISSUE THREAD

**Issue by fortizc** [palaviv/caster#1]
Caster fails when try to get the IP address for its web server. The error occurs when the function `get_internal_ip()` is called [this is the problematic line](https://github.com/palaviv/caster/blob/master/caster.py#L18) this is the error  
```
Traceback (most recent call last):
  File "/usr/local/bin/caster", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/caster.py", line 97, in main
    server_ip = get_internal_ip(dev.host)
  File "/usr/local/lib/python3.5/site-packages/caster.py", line 17, in get_internal_ip
    s.connect((dst_ip, 0))
OSError: [Errno 49] Can't assign requested address
```

**Comment by palaviv** [comment]
On what operating system are you running and which version of python?

**Comment by fortizc** [comment]
OSX 10.11.6 with python 3.5

**Comment by palaviv** [comment]
From what I could fine on the internet you need to reset your network interface (http://superuser.com/questions/702203/strange-network-problems-on-os-x).
In any case I pushed a commit that should make caster listen on all interfaces in `get_internal_ip` fail (27636e9)
